### ISSUE TITLE
Installation / yarn

### ISSUE THREAD

**Issue by mathieugrimault** [abes-esr/algoliens-web#10]
Bonjour, je tente d'installer l'outil mais je bute sur la commande "yarn encore ..." qui me répond un 
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'encore'

Il manque un fichier/dossier au git ? J'ai oublié un truc ? 
Merci d'avance !

**Comment by symac** [comment]
Bonjour @mathieugrimault ,
il manquait en effet une instruction dans le README, après le ```composer install``` il est nécessaire de lancer ```yarn install```. C'est maintenant ( https://github.com/abes-esr/algoliens-web/commit/17254dfe5e106143421dfffc882f50112eaa0a39 ) corrigé dans le README, merci pour le signalement.

L'utilisation de Yarn est d'ailleurs une étape dont l'on peut peut-être se passer, mais ce n'est pas le sujet avec lequel je suis le plus à l'aise et je n'ai pas creusé.

**Comment by mathieugrimault** [comment]
Moi non je ne suis pas un connaisseur de yarn. 

A noter; sous Debian, yarn est fourni par 'cmdtest' qui ne semble pas compatible. J'ai du installer un 'vrai' yarn via npm.

Maintenant, je n'arrive pas à atteindre la page 'admin'. La page public semble bien générée mais sans style. 

Voilà le résultat 
# yarn encore dev
yarn run v1.22.4
$ /var/www/html/algoliens/node_modules/.bin/encore dev
Running webpack ...

 DONE  Compiled successfully in 3272ms                                                                        1:23:15 PM

 I  5 files written to public/build
Entrypoint app [big] = runtime.js app.css app.js
Entrypoint record_view [big] = runtime.js vendors~record_view.js record_view.js
Done in 5.11s.

Le fichier webpack indique bien une entrée /admin mais commentée. Si on décomente et lance le yarn.. il semble manquer fichiers liés : 

Entry module not found: Error: Can't resolve './assets/js/admin.js' in '/var/www/html/algoliens'

**Comment by symac** [comment]
@mathieugrimault non le admin.js est dans la config standard de Symfony mais je ne l'ai pas utilisée. Normalement si tout se passe bien en se rendant sur /admin il est censé rediriger vers /login et demander de s'authentifier. Il n'y a pas de système d'authentification de compte aussi faudrait-il créer un compte avec les instructions contenues dans le README.

Le style de la partie admin est le même que celui de la partie publique, donc normalement rien de particulier à faire de ce côté là.

**Comment by mathieugrimault** [comment]
J'ai buté sur ma méconnaissance de symfony. J'ai du bidouiller le webpack pour que les chemins/url soient raccords et ajouté le support d'un proxy pour les appels à l'abes mais maintenant algoliens semble fonctionnel.
